fix(split pipelines): Use package name instead of package dir, use exact paths
Signed-off-by: RJ Sampson <rj.sampson@chainguard.dev>

diff --git a/pkg/build/pipelines/split/debug.yaml b/pkg/build/pipelines/split/debug.yaml
--- a/pkg/build/pipelines/split/debug.yaml
+++ b/pkg/build/pipelines/split/debug.yaml
@@ -7,31 +7,39 @@ needs:
     - scanelf
 
 inputs:
-  packagedir:
+  package:
     description: |
-      The package directory to split debug files from
-    default: ${{targets.destdir}}
+      The package to split debug files from
+    required: false
 
 pipeline:
-  - if: ${{inputs.packagedir}} != ${{targets.contextdir}}
-    runs: |
-      mkdir -p "${{inputs.packagedir}}/.dbg-tmp"
+  - runs: |
+      PACKAGE_DIR="${{targets.destdir}}"
+      if [ -n "$PACKAGE_DIR" ]; then
+        PACKAGE_DIR="/home/build/melange-out/${{inputs.package}}"
+      fi
+
+      if [ "$PACKAGE_DIR" == "${{targets.contextdir}}" ]; then
+        echo "ERROR: Package can not split files from itself!" && exit 1
+      fi
+
+      mkdir -p "$PACKAGE_DIR/.dbg-tmp"
       # note: the ${{targets.subpkgdir}} doesn't exist when the glob is evaluated
-      scanelf -Ry "${{inputs.packagedir}}"/* | while read type src; do
+      scanelf -Ry "$PACKAGE_DIR"/* | while read type src; do
         if [ "$type" != ET_DYN ]; then
           continue
         fi
-        dst=${{targets.contextdir}}/usr/lib/debug/${src#"${{inputs.packagedir}}"/*/}.debug
+        dst=${{targets.contextdir}}/usr/lib/debug/${src#"$PACKAGE_DIR"/*/}.debug
         mkdir -p "${dst%/*}"
         ino=$(stat -c %i "$src")
-        if ! [ -e "${{inputs.packagedir}}/.dbg-tmp/$ino" ]; then
-          tmp=${{inputs.packagedir}}/.dbg-tmp/${src##*/}
+        if ! [ -e "$PACKAGE_DIR/.dbg-tmp/$ino" ]; then
+          tmp=$PACKAGE_DIR/.dbg-tmp/${src##*/}
           objcopy --only-keep-debug "$src" "$dst"
           objcopy --add-gnu-debuglink="$dst" --strip-unneeded -R .comment "$src" "$tmp"
           # preserve attributes, links
           cat "$tmp" > "$src"
           rm "$tmp"
-          ln "$dst" "${{inputs.packagedir}}/.dbg-tmp/$ino"
+          ln "$dst" "$PACKAGE_DIR/.dbg-tmp/$ino"
         fi
       done
-      rm -r "${{inputs.packagedir}}/.dbg-tmp"
+      rm -r "$PACKAGE_DIR/.dbg-tmp"
diff --git a/pkg/build/pipelines/split/infodir.yaml b/pkg/build/pipelines/split/infodir.yaml
--- a/pkg/build/pipelines/split/infodir.yaml
+++ b/pkg/build/pipelines/split/infodir.yaml
@@ -5,17 +5,25 @@ needs:
     - busybox
 
 inputs:
-  packagedir:
+  package:
     description: |
-      The package directory to split info pages from
-    default: ${{targets.destdir}}
+      The package to split info pages files from
+    required: false
 
 pipeline:
-  - if: ${{inputs.packagedir}} != ${{targets.contextdir}}
-    runs: |
-      if [ -d "${{inputs.packagedir}}/usr/share/info" ]; then
-        rm -f "${{inputs.packagedir}}"/usr/share/info/dir
+  - runs: |
+      PACKAGE_DIR="${{targets.destdir}}"
+      if [ -n "$PACKAGE_DIR" ]; then
+        PACKAGE_DIR="/home/build/melange-out/${{inputs.package}}"
+      fi
+
+      if [ "$PACKAGE_DIR" == "${{targets.contextdir}}" ]; then
+        echo "ERROR: Package can not split files from itself!" && exit 1
+      fi
+
+      if [ -d "$PACKAGE_DIR/usr/share/info" ]; then
+        rm -f "$PACKAGE_DIR"/usr/share/info/dir
 
         mkdir -p "${{targets.contextdir}}/usr/share"
-        mv "${{inputs.packagedir}}"/usr/share/info "${{targets.contextdir}}/usr/share"
+        mv "$PACKAGE_DIR"/usr/share/info "${{targets.contextdir}}/usr/share"
       fi
diff --git a/pkg/build/pipelines/split/manpages.yaml b/pkg/build/pipelines/split/manpages.yaml
--- a/pkg/build/pipelines/split/manpages.yaml
+++ b/pkg/build/pipelines/split/manpages.yaml
@@ -5,15 +5,23 @@ needs:
     - busybox
 
 inputs:
-  packagedir:
+  package:
     description: |
-      The package directory to split manpages from
-    default: ${{targets.destdir}}
+      The package to split manpages from
+    required: false
 
 pipeline:
-  - if: ${{inputs.packagedir}} != ${{targets.contextdir}}
-    runs: |
-      if [ -d "${{inputs.packagedir}}/usr/share/man" ]; then
+  - runs: |
+      PACKAGE_DIR="${{targets.destdir}}"
+      if [ -n "$PACKAGE_DIR" ]; then
+        PACKAGE_DIR="/home/build/melange-out/${{inputs.package}}"
+      fi
+
+      if [ "$PACKAGE_DIR" == "${{targets.contextdir}}" ]; then
+        echo "ERROR: Package can not split files from itself!" && exit 1
+      fi
+
+      if [ -d "$PACKAGE_DIR/usr/share/man" ]; then
         mkdir -p "${{targets.contextdir}}/usr/share"
-        mv "${{inputs.packagedir}}/usr/share/man" "${{targets.contextdir}}/usr/share"
+        mv "$PACKAGE_DIR/usr/share/man" "${{targets.contextdir}}/usr/share"
       fi
diff --git a/pkg/build/pipelines/split/static.yaml b/pkg/build/pipelines/split/static.yaml
--- a/pkg/build/pipelines/split/static.yaml
+++ b/pkg/build/pipelines/split/static.yaml
@@ -5,25 +5,33 @@ needs:
     - busybox
 
 inputs:
-  packagedir:
+  package:
     description: |
-      The package directory to split static library files from
-    default: ${{targets.destdir}}
+      The package to split static library files from
+    required: false
 
 pipeline:
-  - if: ${{inputs.packagedir}} != ${{targets.contextdir}}
-    runs: |
+  - runs: |
+      PACKAGE_DIR="${{targets.destdir}}"
+      if [ -n "$PACKAGE_DIR" ]; then
+        PACKAGE_DIR="/home/build/melange-out/${{inputs.package}}"
+      fi
+
+      if [ "$PACKAGE_DIR" == "${{targets.contextdir}}" ]; then
+        echo "ERROR: Package can not split files from itself!" && exit 1
+      fi
+
       i= j=
-      cd "${{inputs.packagedir}}" || exit 0
+      cd "$PACKAGE_DIR" || exit 0
 
       libdirs=usr/
       [ -d lib/ ] && libdirs="lib/ $libdirs"
       for i in \
         $(find $libdirs -name '*.a' 2>/dev/null); do
-            if [ -e "${{inputs.packagedir}}/$i" ] || [ -L "${{inputs.packagedir}}/$i" ]; then
+            if [ -e "$PACKAGE_DIR/$i" ] || [ -L "$PACKAGE_DIR/$i" ]; then
               d="${{targets.contextdir}}/${i%/*}" # dirname $i
               mkdir -p "$d"
-              mv "${{inputs.packagedir}}/$i" "$d"
-              rmdir "${{inputs.packagedir}}/${i%/*}" 2>/dev/null || :
+              mv "$PACKAGE_DIR/$i" "$d"
+              rmdir "$PACKAGE_DIR/${i%/*}" 2>/dev/null || :
             fi
         done
