Add git-cherry-pick pipeline

diff --git a/pkg/build/pipelines/git-checkout.yaml b/pkg/build/pipelines/git-checkout.yaml
--- a/pkg/build/pipelines/git-checkout.yaml
+++ b/pkg/build/pipelines/git-checkout.yaml
@@ -38,6 +38,10 @@ inputs:
     description: |
       Indicates whether --recurse-submodules should be passed to git clone.
     default: false
+  
+  cherry-picks:
+    description: |
+      List of cherry picks to apply
 
 pipeline:
   - runs: |
@@ -48,9 +52,57 @@ pipeline:
       fail() { msg FAIL "$@"; exit 1; }
       vr() { msg "execute:" "$@"; "$@"; }
 
+      process_cherry_picks() {
+            local cpicksf="$1" oifs="" count=0
+            local fetched_branches=""
+            if [ -z "$cpicksf" ]; then
+                return 0
+            fi
+            if [ ! -f "$cpicksf" ]; then
+                msg "cherry picks input '$cpicksf' is not a file"
+                return 1
+            fi
+
+            local line="" branch="" hash=""
+            while read line; do
+                # drop anything after #
+                line=${line%%#*}
+                [ -z "$line" ] && continue
+                case "$line" in
+                    */*) branch=${line%%/*}; hash=${line#*/};;
+                    *) hash=${line};;
+                esac
+                if [ -n "$branch" ]; then
+                    case " $fetched_branches " in
+                        *) vr git fetch origin $branch:$branch || {
+                            msg "failed to fetch branch $branch"
+                            return 1
+                            }
+                            local fetched_branches="$fetched_branches $branch";;
+                    esac
+                fi
+
+                vr env \
+                GIT_AUTHOR_NAME="Melange Build" \
+                GIT_AUTHOR_EMAIL="melange-build@cgr.dev" \
+                GIT_COMMITTER_DATE="$SOURCE_DATE_EPOCH" \
+                git cherry-pick -x "$hash" || {
+                    msg "failed to cherry-pick $hash from branch $branch"
+                    return 1
+                }
+
+                count=$((count + 1))
+            done < "$cpicksf"
+
+            if [ $count -gt 0 ]; then
+                msg "applied $count cherry-pick(s). head is now $(git rev-parse HEAD)"
+            fi
+        }
+
       main() {
           local repo=$1 dest=${2:-.} depth=${3:-"-1"} branch=$4
           local tag=$5 expcommit=$6 recurse=${7:-false}
+          local cherry_pick="$8"
           msg "repo='$repo' dest='$dest' depth='$depth' branch='$branch'" \
               "tag='$tag' expcommit='$expcommit' recurse='$recurse'"
 
@@ -108,6 +160,7 @@ pipeline:
                       " got $foundcommit"
               fi
               msg "tip of ${branch:-HEAD} is commit $foundcommit"
+              process_cherry_picks "$cherry_pick" || fail "failed to apply cherry-pick"
               return 0
           fi
 
@@ -121,32 +174,45 @@ pipeline:
           foundcommit=$(git rev-parse --verify HEAD)
           if [ -z "$expcommit" ] || [ "$expcommit" = "$foundcommit" ]; then
               msg "tag $tag is $foundcommit"
-              return 0
+          else
+                # If it's a tag, then it could be a lightweight or annotated tag.
+                # Lightweight tags point directly to the commit and do not have
+                # any messages, signatures, or other data.  Annotated tags point
+                # to its own git object containing the tag data, with a reference
+                # to the underlying commit.  We expect most tags to be using
+                # annotated tags.
+                tagobj=$(git rev-parse --verify --end-of-options \
+                    "refs/$remote/tags/$tag")
+                if [ "$expcommit" != "$tagobj" ]; then
+                    [ "$tagobj" != "$expcommit" ] &&
+                        msg "tag object hash was $tagobj"
+                    fail "Expected commit $expcommit for $tag, found $foundcommit"
+                fi
+
+                msg "Warning: The provided expected-commit ($expcommit)"
+                msg "was the hash of the annotated tag object for $tag."
+                msg "Update to set expected-commit to $foundcommit"
           fi
 
-          # If it's a tag, then it could be a lightweight or annotated tag.
-          # Lightweight tags point directly to the commit and do not have
-          # any messages, signatures, or other data.  Annotated tags point
-          # to its own git object containing the tag data, with a reference
-          # to the underlying commit.  We expect most tags to be using
-          # annotated tags.
-          tagobj=$(git rev-parse --verify --end-of-options \
-              "refs/$remote/tags/$tag")
-          if [ "$expcommit" != "$tagobj" ]; then
-              [ "$tagobj" != "$expcommit" ] &&
-                  msg "tag object hash was $tagobj"
-              fail "Expected commit $expcommit for $tag, found $foundcommit"
-          fi
-
-          msg "Warning: The provided expected-commit ($expcommit)"
-          msg "was the hash of the annotated tag object for $tag."
-          msg "Update to set expected-commit to $foundcommit"
+          process_cherry_picks "$cherry_pick" ||
+                fail "failed to apply cherry-pick"
 
           return 0
       }
+
+      cpickf=$(mktemp) || {
+        echo "failed mktemp"
+        exit 1
+      }
+      
+      cat >"$cpickf" <<"END_CHERRY_PICKS"
+      ${{inputs.cherry-picks}}
+      END_CHERRY_PICKS
 
       main \
           "${{inputs.repository}}" "${{inputs.destination}}" \
           "${{inputs.depth}}" "${{inputs.branch}}" \
           "${{inputs.tag}}" "${{inputs.expected-commit}}" \
-          "${{inputs.recurse-submodules}}"
+          "${{inputs.recurse-submodules}}" "$cpickf"
+
+      rm -f "$cpickf"
