use npm-command, add validation, use in example
Signed-off-by: Jason Hall <jason@chainguard.dev>

diff --git a/pkg/build/pipelines/npm/install.yaml b/pkg/build/pipelines/npm/install.yaml
--- a/pkg/build/pipelines/npm/install.yaml
+++ b/pkg/build/pipelines/npm/install.yaml
@@ -2,9 +2,9 @@ name: Install a portable npm package.
 
 needs:
   packages:
-    - nodejs
-    - ${{inputs.command}}
     - busybox
+    - nodejs
+    - ${{inputs.npm-package}}
 
 inputs:
   package:
@@ -26,24 +26,30 @@ inputs:
     description: |
       Space, comma or newline-separated list of package@version to use in npm overrides, e.g. "yargs@^17.0.0 get-stdin@^9.0.0".
 
-  command:
+  npm-package:
     description: |
       The npm command to run.
     default: "npm"
 
 pipeline:
   - runs: |
+      # Require npm-package to be 'npm' or 'pnpm'
+      if [ ! "${{inputs.npm-package}}" == "npm" ] && [ ! "${{inputs.npm-package}}" == "pnpm" ]; then
+          echo "Invalid npm-package '${{inputs.npm-package}}'; must be 'npm' or 'pnpm'."
+          exit 1
+      fi
+
       # Portable global install of the package.
       # Simplest way to get both bin and lib directories installed.
       # Does not support overrides; to be fixed below if needed.
-      ${{inputs.command}} install -g "${{inputs.package}}@${{inputs.version}}" -prefix "${{inputs.prefix}}"
+      ${{inputs.npm-package}} install -g "${{inputs.package}}@${{inputs.version}}" -prefix "${{inputs.prefix}}"
 
       if [ ! "${{inputs.overrides}}" == "" ]; then
           # Move to /lib, which contains the node_modules folder.
           cd "${{inputs.prefix}}/lib"
 
           # Create a package.json with the dependency installed above, at which point
-          # `${{inputs.command}} i --install-strategy=shallow .` will output the exact same content the install above did.
+          # `${{inputs.npm-package}} i --install-strategy=shallow .` will output the exact same content the install above did.
           echo "{
             \"dependencies\": {
               \"${{inputs.package}}\": \"${{inputs.version}}\"
@@ -73,7 +79,7 @@ pipeline:
           rm -rf node_modules
 
           # ... to reinstall non-vulnerable node_modules.
-          ${{inputs.command}} i --install-strategy=shallow .
+          ${{inputs.npm-package}} i --install-strategy=shallow .
 
           # Delete artifacts used for & generated from the override install.
           rm -rf package.json package-lock.json node_modules/.package-lock.json
