fetch: support expected-sha512

diff --git a/pipelines/fetch.yaml b/pipelines/fetch.yaml
--- a/pipelines/fetch.yaml
+++ b/pipelines/fetch.yaml
@@ -18,7 +18,10 @@ inputs:
   expected-sha256:
     description: |
       The expected SHA256 of the downloaded artifact.
-    required: true
+
+  expected-sha512:
+    description: |
+      The expected SHA512 of the downloaded artifact.
 
   uri:
     description: |
@@ -29,7 +32,17 @@ pipeline:
   - runs: |
       wget ${{inputs.uri}}
       bn=$(basename ${{inputs.uri}})
-      printf "%s  %s\n" '${{inputs.expected-sha256}}' $bn | sha256sum -c
+      if [ "${{inputs.expected-sha256}}" != "" ]; then
+        printf "%s  %s\n" '${{inputs.expected-sha256}}' $bn | sha256sum -c
+      fi
+      if [ "${{inputs.expected-sha512}}" != "" ]; then
+        printf "%s  %s\n" '${{inputs.expected-sha512}}' $bn | sha512sum -c
+      fi
+      if [ "${{inputs.expected-sha512}}" == "" && "${{inputs.expected-sha256}}" == "" ]; then
+        printf "One of expected-sha256 or expected-sha512 is required"
+        exit 1
+      fi
+
       if [ "${{inputs.extract}}" = "true" ]; then
         bn=$(basename ${{inputs.uri}})
         tar -x '--strip-components=${{inputs.strip-components}}' -f $bn
